export default {
  namespaced: true,
  isFetchingLoanRequests: false,
  isFetchingLoanDetails: false,
  fetchingSummary: false,
  isFetchingLoanHistory: false,
  Loading: false,
  searchFound: true,
  loanRequests: [],
  loanDetails: {},
  loanHistory: [],
  requestsSummary: {
    total: 0,
    pending: 0,
    approved: 0,
    rejected: 0,
  },
  toast: {
    show: false,
    title: "",
    message: "",
    success: false,
  },
  splitDetails: {
    offerId: "",
    customerName: "",
    firstRowBio: [],
    secondRowBio: [],
    thirdRowBio: [],
    loanDetailsRow: [],
    loanHistory: [],
  },
  searchTerm: "",
  allRepayments: null,
  fetchingRepayments:false,
  fetchingLoansReport:false,
  allLoansReport:null,
  schedule:null,
};